import ImageSection from '@/Ui/ImageSection'
import Image from 'next/image'
import React from 'react'

const page = () => {
  return (
    <div>
        <ImageSection  title={"Document Digitization"}/>
 <div className="bg-gray-50 text-gray-800 px-6 sm:px-12 md:px-24 py-16 space-y-16">

      {/* ================== HERO / JOB INTRO ================== */}
      <section className=" bg-gray-900 text-white text-center max-w-4xl mx-auto space-y-4 py-6">
        <h1 className="text-4xl sm:text-5xl md:text-6xl font-extrabold leading-tight">
          Document Digitization Specialist
        </h1>
        <p className="text-lg sm:text-xl text-gray-200">
          Preserve history and streamline businesses by converting physical documents into digital assets.
        </p>

        <div className="mt-4 flex flex-col sm:flex-row justify-center gap-4 text-sm sm:text-base text-gray-300 font-medium">
          <span>💻 100% Remote Opportunity</span>
          <span>📁 Project-Based Workflow</span>
          <span>🎯 Quality Focused</span>
        </div>
      </section>

      {/* ================== ABOUT THE JOB ROLE ================== */}
      <section className="max-w-5xl mx-auto space-y-6">
        <h2 className="text-2xl sm:text-3xl font-bold text-gray-900">
          About the Job Role
        </h2>
        <p className="text-gray-700 leading-relaxed">
          Hire in Global is looking for meticulous and patient Document Digitization Specialists. In an era where businesses are rapidly moving towards paperless environments, your role is pivotal. You will be responsible for converting physical hard-copy documents into editable, searchable, and organized digital formats.
        </p>
        <p className="text-gray-700 leading-relaxed">
          This role goes beyond simple typing. It involves deciphering complex layouts, understanding handwritten notes, and correcting errors left behind by automated OCR (Optical Character Recognition) software. You will handle sensitive documents ranging from legal contracts and medical records to historical manuscripts and corporate archives.
        </p>
        <p className="text-gray-700 leading-relaxed">
          We are looking for individuals who view accuracy as an art form. If you are the type of person who spots a double-space error in a paragraph or a misspelled word in a headline, this role is tailored for you.
        </p>
      </section>

      {/* ================== KEY RESPONSIBILITIES ================== */}
      <section className="max-w-5xl mx-auto space-y-4">
        <h2 className="text-2xl sm:text-3xl font-bold text-gray-900">Key Responsibilities</h2>
        <ul className="list-disc list-inside text-gray-700 space-y-2">
          <li><strong>Manual Transcription:</strong> Type out text from scanned images (JPG/PNG) into editable Word or Text formats when OCR software fails to capture the nuance of the document.</li>
          <li><strong>OCR Correction:</strong> Review and edit text generated by scanning software to ensure 100% fidelity to the original source material.</li>
          <li><strong>Handwriting Analysis:</strong> Decipher and digitize handwritten notes, memos, and forms, converting them into clear, digital text.</li>
          <li><strong>Formatting & Layout:</strong> Recreate the formatting of the original document, including tables, bullet points, and headers, using Microsoft Word.</li>
          <li><strong>File Organization:</strong> Name, sort, and save files according to specific project indexing guidelines to ensure easy retrieval.</li>
          <li><strong>Quality Assurance:</strong> Conduct side-by-side comparisons of the original image and the digitized file to eliminate discrepancies.</li>
          <li><strong>Confidentiality Maintenance:</strong> Adhere to strict privacy agreements (NDAs) when handling sensitive client data, such as personal IDs or financial records.</li>
          <li><strong>Project Communication:</strong> Report progress daily and flag unreadable or corrupted source files to the supervisor immediately.</li>
        </ul>
      </section>

      {/* ================== QUALIFICATIONS & REQUIREMENTS ================== */}
      <section className="max-w-5xl mx-auto space-y-4">
        <h2 className="text-2xl sm:text-3xl font-bold text-gray-900">Qualifications & Requirements</h2>
        <ul className="list-disc list-inside text-gray-700 space-y-2">
          <li><strong>Critical Skill:</strong> Attention to Detail — Candidates must replicate documents with 98-100% accuracy. Speed is secondary.</li>
          <li><strong>Educational Background:</strong> Minimum High School Diploma or equivalent. Certification in data entry or computer applications is a plus.</li>
          <li><strong>Typing Skills:</strong> Steady typing speed (minimum 30 WPM recommended) with exceptional accuracy.</li>
          <li><strong>Software Proficiency:</strong> Advanced knowledge of MS Word (styles, tables, formatting) and basic familiarity with PDF tools (Adobe Acrobat) and WinZip/WinRAR.</li>
          <li><strong>Language Proficiency:</strong> Excellent command of English spelling and grammar.</li>
          <li><strong>Visual Acuity:</strong> Ability to read various fonts, low-quality scans, and cursive handwriting for extended periods.</li>
          <li><strong>Technical Setup:</strong> Reliable PC/Laptop (Windows 10+ preferred) and high-speed internet for large file transfers.</li>
          <li><strong>Soft Skills:</strong> Patience, integrity, and strong time management skills.</li>
        </ul>
      </section>

      {/* ================== WHY JOIN OUR DIGITIZATION TEAM ================== */}
      <section className="max-w-5xl mx-auto space-y-4">
        <h2 className="text-2xl sm:text-3xl font-bold text-gray-900">
          Why Join Our Digitization Team?
        </h2>
        <p className="text-gray-700 leading-relaxed">
          We believe in rewarding precision and dedication. Here is what we bring to the table:
        </p>
        <ul className="list-disc list-inside text-gray-700 space-y-2">
          <li><strong>Work-Life Balance:</strong> No fixed shifts. Log in and work whenever you are most productive, as long as project deadlines are met.</li>
          <li><strong>Consistent Work Flow:</strong> We serve major B2B clients, ensuring a steady stream of E-Books, legal documents, and corporate files for digitization.</li>
          <li><strong>Performance Bonuses:</strong> High-accuracy submissions are eligible for "Quality Bonuses" on top of the standard page rate.</li>
          <li><strong>Career Progression:</strong> Top performers are promoted to "Quality Analyst" roles, where you review the work of junior typists.</li>
          <li><strong>Hassle-Free Payouts:</strong> Payments are processed securely via Bank Transfer or UPI.</li>
        </ul>
      </section>

      {/* ================== CTA ================== */}
      <div className=' relative  overflow-hidden'>
        <div className="absolute inset-0 z-10 ">
                            <Image
                              src="/data-entry.jpg" // Replace with your image path
                              alt="Why Us Background"
                              fill
                              className="object-cover"
                              priority
                            />
                            {/* Optional overlay for glass/frosted effect */}
                            <div className="absolute inset-0 bg-black/40 "></div>
                          </div>
      <section className=" relative z-10 text-center max-w-3xl mx-auto space-y-4 py-6">
        <h3 className="text-2xl sm:text-3xl font-bold text-gray-300">Help Us Go Paperless</h3>
        <p className="text-gray-300">
          If you have the patience and the eye for detail required for this role, submit your application today.
        </p>
        <button className="px-8 py-4 bg-indigo-600 text-white rounded-2xl font-semibold shadow-lg hover:bg-indigo-700 hover:scale-105 transition-all duration-300">
          Apply Now via Email
        </button>
        <p className="mt-2 text-sm text-gray-300">
          Clicking above will open your email app with a pre-filled template.
        </p>
      </section>
      </div>
</div>
    </div>
  )
}

export default page
